nacos:
  config:
    server-addr: 127.0.0.1:8848

gateway:
  scan-packages: me.sxl
  loadbalance: RoundRobin
  registry:
    # 配置中心方式,默认nacos,可选redis/zookeeper
    protocol: nacos
    nacos-data: testData
    nacos-group: testGroup
#    protocol: redis
#    protocol: zookeeper
    # dubbo注册中心配置,暂时只支持zookeeper
    addrs:
      - id: zk1
        address: 127.0.0.1:2181
#      - id: zk2
#        address: 127.0.0.1:2182
#      - id: zk3
#        address: 127.0.0.1:2183
