server:
  port: 9999

spring:
  application:
    name: gateway
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:user
    username: root
    password: 123456

mybatis:
  configuration:
    use-actual-param-name: false

dubbo:
  reference:
    registry:
      protocol: zookeeper
      addrs:
        - id: zk1
          address: 127.0.0.1:2181
        - id: zk2
          address: 127.0.0.1:2182
        - id: zk3
          address: 127.0.0.1:2183

rsa:
  key:
    private: